# Generated by Django 3.2.15 on 2022-08-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_order_name_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='refund',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
